# Generated by Django 5.1.4 on 2025-01-10 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=50, null=True)),
                ('data_played', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('steamid', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('auth_code', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(max_length=10)),
                ('team', models.CharField(max_length=20)),
                ('kills', models.SmallIntegerField()),
                ('assists', models.SmallIntegerField()),
                ('deaths', models.SmallIntegerField()),
                ('adr', models.FloatField()),
                ('kast', models.FloatField()),
                ('impact', models.FloatField()),
                ('rating', models.FloatField()),
                ('clutches_1x1', models.SmallIntegerField()),
                ('clutches_1x2', models.SmallIntegerField()),
                ('clutches_1x3', models.SmallIntegerField()),
                ('clutches_1x4', models.SmallIntegerField()),
                ('clutches_1x5', models.SmallIntegerField()),
                ('first_kills', models.SmallIntegerField()),
                ('first_deaths', models.SmallIntegerField()),
                ('utility_damage', models.SmallIntegerField()),
                ('enemy_flashed', models.SmallIntegerField()),
                ('flash_assists', models.SmallIntegerField()),
                ('demo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='demo_database.demo')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='demo_database.player')),
            ],
        ),
    ]
