# Generated by Django 5.1.4 on 2025-02-05 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('equipment_value_from', models.IntegerField()),
                ('equipment_value_to', models.IntegerField()),
                ('is_pistol', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HitGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='MatchType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
                ('is_elo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MMRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('steamid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('auth_code', models.CharField(blank=True, max_length=50, null=True)),
                ('last_nickname', models.CharField(max_length=32)),
                ('last_avatar', models.CharField(max_length=255)),
                ('date_check', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Side',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='WeaponType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='WinReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(max_length=64, unique=True)),
                ('sharecode', models.CharField(blank=True, max_length=50, null=True)),
                ('data_played', models.DateTimeField(blank=True, null=True)),
                ('win_team', models.CharField(blank=True, max_length=32, null=True)),
                ('score_win', models.SmallIntegerField()),
                ('score_lose', models.SmallIntegerField()),
                ('map_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='demo_database.map')),
                ('match_type_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='demo_database.matchtype')),
            ],
        ),
        migrations.CreateModel(
            name='Duels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kills', models.IntegerField()),
                ('open_kills', models.IntegerField()),
                ('demo_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='demo_database.demo')),
                ('attacker_player_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='attacker', to='demo_database.player')),
                ('victim_player_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='victim', to='demo_database.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerInDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=20)),
                ('crosshair_code', models.CharField(max_length=40)),
                ('elo_old', models.IntegerField(blank=True, null=True)),
                ('elo_new', models.IntegerField(blank=True, null=True)),
                ('demo_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='demo_database.demo')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='demo_database.player')),
                ('rang_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='demo_database.mmrank')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerWeaponStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fires_count', models.IntegerField()),
                ('demo_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='demo_database.demo')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='demo_database.player')),
                ('side_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='demo_database.side')),
                ('weapon_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='demo_database.weapon')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerHitgroupStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage', models.IntegerField()),
                ('hits', models.IntegerField()),
                ('kills', models.IntegerField()),
                ('hit_group_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='demo_database.hitgroup')),
                ('player_weapon_stat_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='demo_database.playerweaponstat')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rounds', models.IntegerField()),
                ('kills', models.SmallIntegerField()),
                ('assists', models.SmallIntegerField()),
                ('deaths', models.SmallIntegerField()),
                ('damage', models.IntegerField()),
                ('kast_rounds', models.IntegerField()),
                ('win_clutches_1x1', models.SmallIntegerField()),
                ('win_clutches_1x2', models.SmallIntegerField()),
                ('win_clutches_1x3', models.SmallIntegerField()),
                ('win_clutches_1x4', models.SmallIntegerField()),
                ('win_clutches_1x5', models.SmallIntegerField()),
                ('loss_clutches_1x1', models.SmallIntegerField()),
                ('loss_clutches_1x2', models.SmallIntegerField()),
                ('loss_clutches_1x3', models.SmallIntegerField()),
                ('loss_clutches_1x4', models.SmallIntegerField()),
                ('loss_clutches_1x5', models.SmallIntegerField()),
                ('kills_1', models.SmallIntegerField()),
                ('kills_2', models.SmallIntegerField()),
                ('kills_3', models.SmallIntegerField()),
                ('kills_4', models.SmallIntegerField()),
                ('kills_5', models.SmallIntegerField()),
                ('first_kills', models.SmallIntegerField()),
                ('first_deaths', models.SmallIntegerField()),
                ('utility_damage', models.SmallIntegerField()),
                ('enemy_flashed', models.SmallIntegerField()),
                ('flash_assists', models.SmallIntegerField()),
                ('impact', models.FloatField()),
                ('rating', models.FloatField()),
                ('buy_type_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='buy_type', to='demo_database.buytype')),
                ('enemy_buy_type_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='emnemy_buy_type', to='demo_database.buytype')),
                ('player_in_demo_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='demo_database.playerindemo')),
                ('side_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='demo_database.side')),
            ],
        ),
        migrations.AddField(
            model_name='weapon',
            name='weapon_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='demo_database.weapontype'),
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.SmallIntegerField()),
                ('win_team', models.CharField(max_length=32)),
                ('ct_buy_type_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='t_buy_type', to='demo_database.buytype')),
                ('demo_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='demo_database.demo')),
                ('t_buy_type_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ct_buy_type', to='demo_database.buytype')),
                ('win_side_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='demo_database.side')),
                ('win_reason_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='demo_database.winreason')),
            ],
        ),
    ]
