# Generated by Django 5.1.4 on 2025-04-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_match_steam_sharecode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
