# Generated by Django 5.1.4 on 2025-05-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_avatar_big',
            field=models.CharField(default='big', max_length=255),
            preserve_default=False,
        ),
    ]
