# Generated by Django 5.1.4 on 2025-05-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
