# Generated by Django 5.1.4 on 2025-01-12 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scoreboard',
            old_name='player',
            new_name='steamid',
        ),
    ]
