# Generated by Django 5.1.4 on 2025-01-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_database', '0002_rename_player_scoreboard_steamid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='steamid',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
