# Generated by Django 5.1.4 on 2025-05-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_database', '0002_player_last_match_steam_sharecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
