# Generated by Django 5.1.4 on 2025-05-05 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_database', '0002_map_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mmrank',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='duels',
            name='demo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo_database.demo'),
        ),
        migrations.AlterField(
            model_name='playerhitgroupstat',
            name='player_weapon_stat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hitgroup_stat', to='demo_database.playerweaponstat'),
        ),
        migrations.AlterField(
            model_name='playerindemo',
            name='demo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo_database.demo'),
        ),
        migrations.AlterField(
            model_name='playerweaponstat',
            name='demo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo_database.demo'),
        ),
        migrations.AlterField(
            model_name='round',
            name='demo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo_database.demo'),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='player_in_demo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo_database.playerindemo'),
        ),
    ]
