# Generated by Django 5.1.4 on 2025-05-09 16:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_database', '0002_player_last_avatar_big'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demo',
            name='uploaded_by',
        ),
        migrations.AddField(
            model_name='demo',
            name='uploaded_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
