# Generated by Django 5.1.4 on 2025-05-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_database', '0003_weapon_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='winreason',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
