# Generated by Django 5.1.4 on 2025-05-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_database', '0004_winreason_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='win_team_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
