# Generated by Django 5.1.4 on 2025-05-07 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_database', '0004_demo_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerindemo',
            name='demo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='demo_database.demo'),
        ),
        migrations.AlterField(
            model_name='playerindemo',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='demos', to='demo_database.player'),
        ),
    ]
